### ISSUE TITLE
What is the purpose of this project?

### ISSUE THREAD

**Issue by WinstonLai** [weiweihuanghuang/Times-New-Bastard#6]
May I ask the purpose of this project? I am sorry that I do not understand how to make use of it in any work. Would appreciate anyone to tell me. Thank you!

**Comment by weiweihuanghuang** [comment]
You can install it on your computer and use it in any text environment so that the every seventh letter is jarringly sans serif!

**Comment by WinstonLai** [comment]
Yeah, thank you. I understand what this repo does. I'm just curious the actual use case of turning every seventh letter as jarringly sans serif. I feel that it would be good for you to elaborate a bit more practical use cases in your read me markdown so other people would appreciate your work more. Personally I'm interested in background of the idea, too. If this is just something for fun, then please add it in your read me description, too. It will help other people understand the purpose of this repo.

**Comment by weiweihuanghuang** [comment]
I don't think there's much to explain! See the screenshots posted on the read me. Maybe it's funny for some people, maybe it's serious. I don't mind.

**Comment by WinstonLai** [comment]
Thank you for the clarification!
